name: activ8
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  app_settings: ^5.1.1
  day_night_time_picker: ^1.3.0+1
  collection: ^1.18.0
  dots_indicator: ^3.0.0
  email_validator: ^2.1.17
  flutter_rating_bar: ^4.0.1
  fuzzywuzzy: ^1.1.6
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  health: ^8.1.0
  http: ^1.2.0
  intl: ^0.18.0
  logger: ^2.0.2+1
  material_symbols_icons: ^4.2719.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_gauges: ^24.2.4
  time_range_picker: ^2.2.0
  units_converter: ^3.0.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dependency_validator: ^3.2.3
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/menu_data.json


flutter_launcher_icons:
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
